CREATE TABLE user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) DEFAULT NULL
);


CREATE TABLE todo (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(255) DEFAULT NULL,
    week BIGINT DEFAULT NULL
);

CREATE TABLE user_todo (
    user_id BIGINT NOT NULL,
    todo_id BIGINT NOT NULL,
    CONSTRAINT FK_USER_ID FOREIGN KEY (user_id) REFERENCES user (id),
    CONSTRAINT FK_TODO_ID FOREIGN KEY (todo_id) REFERENCES todo (id)
);